In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import os

In [2]:
#importing crime data
crime = pd.read_csv(os.path.join("combo_crime_data.csv"))

In [3]:
crime.head()

,ID,Case_Number,Date,Block,IUCR,Primary_Type,Description,Location_Description,Arrest,Domestic,...,Community_Area,FBI_Code,X_Coordinate,Y_Coordinate,Year,Updated_On,Latitude,Longitude,Location,Community_Area_Name
0,24026,JB322801,6/25/18 23:50,123XX S YALE AVE,110,HOMICIDE,FIRST DEGREE MURDER,STREET,False,False,...,53.0,01A,1176840.0,1823147.0,2018,7/2/18 15:51,41.670053,-87.628426,"(41.670052557, -87.6284259)",West Pullman
1,11359886,JB322747,6/25/18 22:04,001XX W BRAYTON ST,486,BATTERY,DOMESTIC BATTERY SIMPLE,RESIDENCE,False,True,...,53.0,08B,1177738.0,1821460.0,2018,7/2/18 15:51,41.665403,-87.625190,"(41.665402959, -87.625190065)",West Pullman
2,11359755,JB322421,6/25/18 17:28,122XX S PARNELL AVE,460,BATTERY,SIMPLE,SIDEWALK,False,False,...,53.0,08B,1174847.0,1823794.0,2018,7/2/18 15:51,41.671873,-87.635701,"(41.671872535, -87.635700877)",West Pullman
3,11359650,JB322719,6/25/18 21:57,002XX W 119TH ST,2027,NARCOTICS,POSS: CRACK,SIDEWALK,True,False,...,53.0,18,1176651.0,1826025.0,2018,7/2/18 15:51,41.677954,-87.629032,"(41.677954481, -87.629031525)",West Pullman
4,11359309,JB322038,6/25/18 14:24,122XX S NORMAL AVE,051A,ASSAULT,AGGRAVATED: HANDGUN,PARK PROPERTY,False,False,...,53.0,04A,1175177.0,1823767.0,2018,7/2/18 15:51,41.671791,-87.634494,"(41.671791105, -87.634493883)",West Pullman

In [4]:
crime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 121696 entries, 0 to 121695
Data columns (total 23 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   ID                    121696 non-null  int64
 1   Case_Number           121695 non-null  object
 2   Date                  121696 non-null  object
 3   Block                 121696 non-null  object
 4   IUCR                  121696 non-null  object
 5   Primary_Type          121696 non-null  object
 6   Description           121696 non-null  object
 7   Location_Description  121423 non-null  object
 8   Arrest                121696 non-null  bool
 9   Domestic              121696 non-null  bool
 10  Beat                  121696 non-null  int64
 11  District              121696 non-null  int64
 12  Ward                  121696 non-null  float64
 13  Community_Area        121696 non-null  float64
 14  FBI_Code              121696 non-null  object
 15  X_Coordinate          120991 non-null  float64
 16  Y_Coordinate          120991 non-null  float64
 17  Year                  121696 non-null  int64
 18  Updated_On            121696 non-null  object
 19  Latitude              120991 non-null  float64
 20  Longitude             120991 non-null  float64
 21  Location              120991 non-null  object
 22  Community_Area_Name   121696 non-null  object
dtypes: bool(2), float64(6), int64(4), object(11)
memory usage: 19.7+ MB

In [5]:
#getting rid of columns that we cant do git dummies on
crime_cleaned = crime.drop(["Date", "ID", "Case_Number", "Block", "IUCR", "Description", "X_Coordinate", "Y_Coordinate", "Year", "Updated_On", "Latitude", "Longitude", "Location"], axis=1)

In [6]:
crime_cleaned.dtypes

Primary_Type             object
Location_Description     object
Arrest                     bool
Domestic                   bool
Beat                      int64
District                  int64
Ward                    float64
Community_Area          float64
FBI_Code                 object
Community_Area_Name      object
dtype: object

In [ ]:
#crime_cleaned.dtypes

In [7]:
#making dummy variables out of the object variables 
crime_dummies= pd.get_dummies(crime_cleaned)
crime_dummies.head()

,Arrest,Domestic,Beat,District,Ward,Community_Area,Primary_Type_ARSON,Primary_Type_ASSAULT,Primary_Type_BATTERY,Primary_Type_BURGLARY,...,Community_Area_Name_Washington Heights,Community_Area_Name_Washington Park,Community_Area_Name_West Elsdon,Community_Area_Name_West Englewood,Community_Area_Name_West Garfield Park,Community_Area_Name_West Lawn,Community_Area_Name_West Pullman,Community_Area_Name_West Ridge,Community_Area_Name_West Town,Community_Area_Name_Woodlawn
0,False,False,523,5,34.0,53.0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
1,False,True,523,5,9.0,53.0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,0
2,False,False,523,5,34.0,53.0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,0
3,True,False,522,5,34.0,53.0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
4,False,False,523,5,34.0,53.0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0

In [8]:
# Assign X (data) and y (target)
X = crime_dummies.drop("Arrest", axis=1)
y = crime_dummies["Arrest"]
print(X.shape, y.shape)

(121696, 261) (121696,)

In [9]:
from sklearn.model_selection import train_test_split
#strafity helps to make the data more random

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, stratify=y)

In [10]:
#create a logisitc regression model 
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(solver='lbfgs', max_iter=1000)
classifier

LogisticRegression(max_iter=1000)

In [11]:
#fit (train) model with training data 
classifier.fit(X_train, y_train)
classifier.score(X_test, y_test)

0.8775637654483303

In [12]:
#validata model using test data
print(f"Training Data Score: {classifier.score(X_train, y_train)}")
print(f"Testing Data Score: {classifier.score(X_test, y_test)}")

Training Data Score: 0.877059777368744
Testing Data Score: 0.8775637654483303

In [13]:
#validata model using test data
#
print(f"Training Data Score: {classifier.score(X_train, y_train)}")
print(f"Testing Data Score: {classifier.score(X_test, y_test)}")

Training Data Score: 0.877059777368744
Testing Data Score: 0.8775637654483303

In [15]:
#make predictions 
predictions = classifier.predict(X_test)
print(f"First 10 Predictions:   {predictions[:10]}")
print(f"First 10 Actual labels: {y_test[:10].tolist()}")

First 10 Predictions:   [False False False  True False False False False False False]
First 10 Actual labels: [False, False, False, True, True, True, False, False, False, False]

In [16]:
pd.DataFrame({"Prediction": predictions, "Actual": y_test}).reset_index(drop=True)

       Prediction  Actual
0           False   False
1           False   False
2           False   False
3            True    True
4           False    True
...           ...     ...
30419       False   False
30420        True    True
30421       False   False
30422       False   False
30423       False   False

[30424 rows x 2 columns]

In [17]:
#### random forest 
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=200)
rf = rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.8678017354719958

In [18]:
print(f"Training Data Score: {rf.score(X_train, y_train)}")
print(f"Testing Data Score: {rf.score(X_test, y_test)}")

Training Data Score: 0.9392803926724516
Testing Data Score: 0.8678017354719958

In [19]:
predictions = rf.predict(X_test)
print(f"First 10 Predictions:   {predictions[:10]}")
print(f"First 10 Actual labels: {y_test[:10].tolist()}")

First 10 Predictions:   [False False False  True False  True  True False False  True]
First 10 Actual labels: [False, False, False, True, True, True, False, False, False, False]

In [20]:
pd.DataFrame({"Prediction": predictions, "Actual": y_test}).reset_index(drop=True)

       Prediction  Actual
0           False   False
1           False   False
2           False   False
3            True    True
4           False    True
...           ...     ...
30419       False   False
30420        True    True
30421       False   False
30422       False   False
30423       False   False

[30424 rows x 2 columns]

In [21]:
feature_names = X.columns

sorted(zip(rf.feature_importances_, feature_names), reverse=True)

[(0.1382384293439225, 'Beat'),
 (0.11179244036352745, 'FBI_Code_18'),
 (0.10992223679332867, 'Primary_Type_NARCOTICS'),
 (0.06139327184383945, 'Ward'),
 (0.025901178627858786, 'Primary_Type_CRIMINAL TRESPASS'),
 (0.025550485770658164, 'Community_Area'),
 (0.024092985709236417, 'District'),
 (0.022851888187182392, 'Primary_Type_WEAPONS VIOLATION'),
 (0.022840141629071508, 'Domestic'),
 (0.02103148982492385, 'FBI_Code_15'),
 (0.018933997337283875, 'Location_Description_STREET'),
 (0.01811956614470635, 'Location_Description_DEPARTMENT STORE'),
 (0.01677991550968788, 'Location_Description_GROCERY FOOD STORE'),
 (0.016568185721585974, 'FBI_Code_24'),
 (0.014702898560782184, 'Location_Description_RESIDENCE'),
 (0.013378766835418223, 'Location_Description_SIDEWALK'),
 (0.01152017405882114, 'Primary_Type_INTERFERENCE WITH PUBLIC OFFICER'),
 (0.011410261846648164, 'Location_Description_APARTMENT'),
 (0.010960644898677815, 'FBI_Code_26'),
 (0.008801275723021619, 'FBI_Code_6'),
 (0.008494483229738909, 'Primary_Type_THEFT'),
 (0.007765411101548315, 'Primary_Type_BATTERY'),
 (0.007668944320886112, 'FBI_Code_16'),
 (0.007165713832622003, 'Location_Description_SMALL RETAIL STORE'),
 (0.006705370779236344, 'Primary_Type_OTHER OFFENSE'),
 (0.0064324870804711425, 'Primary_Type_CRIMINAL DAMAGE'),
 (0.006076536999795773, 'FBI_Code_14'),
 (0.005940878848311541, 'Location_Description_OTHER'),
 (0.005779398233008327, 'Primary_Type_PROSTITUTION'),
 (0.005641896104414756, 'FBI_Code_08B'),
 (0.005581330867771441, 'Primary_Type_DECEPTIVE PRACTICE'),
 (0.0054450766076595035,
  'Location_Description_PARKING LOT/GARAGE(NON.RESID.)'),
 (0.004961191966127532, 'Location_Description_RESTAURANT'),
 (0.004812597592529071, 'Location_Description_ALLEY'),
 (0.004750087698082331, 'Location_Description_SCHOOL, PUBLIC, BUILDING'),
 (0.004645148486274565, 'Location_Description_RESIDENTIAL YARD (FRONT/BACK)'),
 (0.004435113725287261, 'Location_Description_RESIDENCE PORCH/HALLWAY'),
 (0.004328984494095297, 'Location_Description_CONVENIENCE STORE'),
 (0.00432888186165912, 'Location_Description_VEHICLE NON-COMMERCIAL'),
 (0.004283161749675604, 'Location_Description_GAS STATION'),
 (0.004072016427889131, 'Primary_Type_PUBLIC PEACE VIOLATION'),
 (0.003956557463882666, 'FBI_Code_11'),
 (0.0037325356077856616, 'Primary_Type_ROBBERY'),
 (0.0037046369911221053, 'FBI_Code_08A'),
 (0.0036938971377526463, 'Location_Description_CTA STATION'),
 (0.0036635850723965753, 'FBI_Code_5'),
 (0.003614654228725166, 'Primary_Type_ASSAULT'),
 (0.0035653558753715245, 'Location_Description_DRUG STORE'),
 (0.0031957299333283742, 'FBI_Code_04B'),
 (0.0031483640482070216, 'FBI_Code_3'),
 (0.002779488092546858, 'Primary_Type_BURGLARY'),
 (0.0027702554521611094, 'FBI_Code_7'),
 (0.0027581958039369875, 'Community_Area_Name_North Lawndale'),
 (0.0027329585229430705, 'Primary_Type_MOTOR VEHICLE THEFT'),
 (0.0026623237799570263, 'FBI_Code_22'),
 (0.002625637481321737, 'FBI_Code_04A'),
 (0.0024074368006747515,
  'Location_Description_POLICE FACILITY/VEH PARKING LOT'),
 (0.002348937577843464, 'Primary_Type_LIQUOR LAW VIOLATION'),
 (0.0022525010110535535, 'Location_Description_CTA PLATFORM'),
 (0.002224410015175694, 'Community_Area_Name_Austin'),
 (0.002041864387272244, 'Community_Area_Name_Roseland'),
 (0.0019472112515001925, 'Community_Area_Name_Humboldt Park'),
 (0.0019419122207018405, 'Location_Description_SCHOOL, PUBLIC, GROUNDS'),
 (0.001908685282767837, 'Community_Area_Name_Near West Side'),
 (0.001872154526546224, 'Location_Description_BAR OR TAVERN'),
 (0.0018143525305218452, 'Location_Description_RESIDENCE-GARAGE'),
 (0.0017594307243216807, 'Community_Area_Name_West Garfield Park'),
 (0.001677222273665445, 'Location_Description_PARK PROPERTY'),
 (0.0015944199459923636, 'Community_Area_Name_Greater Grand Crossing'),
 (0.0015920327037887614, 'Location_Description_CTA BUS'),
 (0.0015600338070400179, 'FBI_Code_19'),
 (0.0015462685493760086, 'Primary_Type_GAMBLING'),
 (0.0015455003497656893, 'Location_Description_COMMERCIAL / BUSINESS OFFICE'),
 (0.0015377585745105647, 'Location_Description_HOTEL/MOTEL'),
 (0.0015329278523780986, 'Location_Description_HOSPITAL BUILDING/GROUNDS'),
 (0.0014926723668803258, 'Community_Area_Name_Chatham'),
 (0.0014570753937107536, 'Community_Area_Name_South Shore'),
 (0.0014346880456094296, 'Community_Area_Name_Auburn Gresham'),
 (0.0014072176982754129, 'Community_Area_Name_Englewood'),
 (0.0013633692100683769, 'Location_Description_TAVERN/LIQUOR STORE'),
 (0.001361677116572072, 'Community_Area_Name_West Englewood'),
 (0.0013613167969841347, 'Community_Area_Name_West Town'),
 (0.0013474308565674569, 'Community_Area_Name_Near North Side'),
 (0.0013403903059899486, 'Location_Description_CTA TRAIN'),
 (0.0013140516498614484, 'Community_Area_Name_New City'),
 (0.0012941658507990888, 'Community_Area_Name_East Garfield Park'),
 (0.001289776574025892, 'Community_Area_Name_Logan Square'),
 (0.001278729615279761, 'Community_Area_Name_Pullman'),
 (0.001256646471945487, 'Primary_Type_OBSCENITY'),
 (0.001254813171414194, 'Location_Description_SCHOOL, PRIVATE, BUILDING'),
 (0.0012513908950299642, 'Location_Description_CHA APARTMENT'),
 (0.0011897712453808815, 'Community_Area_Name_South Chicago'),
 (0.0011590876439696773, 'Community_Area_Name_South Lawndale'),
 (0.0011421816811131966, 'Community_Area_Name_Loop'),
 (0.0011112163394284293, 'Community_Area_Name_West Pullman'),
 (0.0010692730388530006, 'Location_Description_GOVERNMENT BUILDING/PROPERTY'),
 (0.001060062606671668, 'Community_Area_Name_Lake View'),
 (0.0010529237562416944, 'Community_Area_Name_Chicago Lawn'),
 (0.001034849028117662, 'Community_Area_Name_Woodlawn'),
 (0.0010320151404696557, 'Location_Description_CHA PARKING LOT/GROUNDS'),
 (0.0010313381564157518, 'Community_Area_Name_Belmont Cragin'),
 (0.001028954478339061, 'Primary_Type_OFFENSE INVOLVING CHILDREN'),
 (0.0010179606737509687, 'Community_Area_Name_South Deering'),
 (0.0009782857938581944, 'FBI_Code_20'),
 (0.0009554555711676065, 'Community_Area_Name_Gage Park'),
 (0.0009327763559575228, 'Community_Area_Name_Uptown'),
 (0.0009206630608634506, 'Community_Area_Name_Lower West Side'),
 (0.0009189541936303016, 'Community_Area_Name_West Lawn'),
 (0.0009073395330179642, 'Community_Area_Name_Washington Park'),
 (0.0008847209317827117,
  'Location_Description_CHURCH/SYNAGOGUE/PLACE OF WORSHIP'),
 (0.0008799898223118037, 'Community_Area_Name_Lincoln Square'),
 (0.0008761363247418616, 'Community_Area_Name_Avondale'),
 (0.0008733246519640585, 'Community_Area_Name_Irving Park'),
 (0.0008665391705004339, 'Community_Area_Name_Morgan Park'),
 (0.0008642121091475351, 'Community_Area_Name_Portage Park'),
 (0.0008634222027864442, 'Community_Area_Name_Brighton Park'),
 (0.0008617666692512473, 'Community_Area_Name_Bridgeport'),
 (0.0008617211700103929, 'Community_Area_Name_Washington Heights'),
 (0.0008517305035236315, 'Community_Area_Name_Lincoln Park'),
 (0.0008474700140829751, 'Primary_Type_CONCEALED CARRY LICENSE VIOLATION'),
 (0.0008377299065171317, 'Community_Area_Name_Grand Boulevard'),
 (0.0008289821831390308, 'Location_Description_CTA BUS STOP'),
 (0.0008275469296050008, 'Community_Area_Name_Douglas'),
 (0.0008201741530678038, 'Community_Area_Name_Ashburn'),
 (0.0007835278837350615, 'Community_Area_Name_Armour Square'),
 (0.0007560472734954752, 'FBI_Code_2'),
 (0.0007548219673142614, 'FBI_Code_17'),
 (0.000744381645437247, 'Community_Area_Name_Rogers Park'),
 (0.0007379568054907181, 'Location_Description_NURSING HOME/RETIREMENT HOME'),
 (0.0007290660116963818,
  'Location_Description_OTHER RAILROAD PROP / TRAIN DEPOT'),
 (0.0007250700686398341, 'Location_Description_BANK'),
 (0.0007221432163736539, 'Location_Description_DRIVEWAY - RESIDENTIAL'),
 (0.0007160556409621235, 'Location_Description_LIBRARY'),
 (0.0006993988915810258, 'Community_Area_Name_Garfield Ridge'),
 (0.0006972419081510939, 'Community_Area_Name_Albany Park'),
 (0.0006967602568331974, 'Community_Area_Name_West Ridge'),
 (0.0006754029336793257, 'Primary_Type_SEX OFFENSE'),
 (0.0006735129555855198, 'Community_Area_Name_Calumet Heights'),
 (0.0006665690069092307, 'Community_Area_Name_East Side'),
 (0.000650968542672411, 'Location_Description_VACANT LOT/LAND'),
 (0.0006438705840489897, 'Community_Area_Name_Hermosa'),
 (0.0006418605044691728, 'Community_Area_Name_Avalon Park'),
 (0.0006086273969116672, 'Community_Area_Name_Fuller Park'),
 (0.0006037388341326612, 'Community_Area_Name_Dunning'),
 (0.0005897950392142119, 'Community_Area_Name_Near South Side'),
 (0.0005896883855483643, 'Community_Area_Name_Edgewater'),
 (0.0005681610921527106, 'Location_Description_BARBERSHOP'),
 (0.0005630289153229768, 'Location_Description_APPLIANCE STORE'),
 (0.0005595341693377905, 'Community_Area_Name_West Elsdon'),
 (0.0005570934531443053, 'Primary_Type_CRIM SEXUAL ASSAULT'),
 (0.0005429794252964259, 'Location_Description_TAXICAB'),
 (0.0005364213391249083, 'Community_Area_Name_McKinley Park'),
 (0.0005233444872105237, 'Community_Area_Name_Kenwood'),
 (0.0005225199341332915, 'Community_Area_Name_Archer Heights'),
 (0.0005213505318695606, 'Community_Area_Name_Riverdale'),
 (0.000509067757373293, "Community_Area_Name_O'Hare"),
 (0.0005015110631509548, 'Location_Description_ABANDONED BUILDING'),
 (0.000500073094252274, 'Location_Description_CTA GARAGE / OTHER PROPERTY'),
 (0.0004956053914834512, 'FBI_Code_10'),
 (0.00048634115243412923, 'Community_Area_Name_North Park'),
 (0.0004844734684695812, 'Location_Description_AUTO / BOAT / RV DEALERSHIP'),
 (0.0004827047509703, 'Location_Description_CONSTRUCTION SITE'),
 (0.0004682197700813449, 'FBI_Code_01A'),
 (0.0004651705790321605, 'Community_Area_Name_Hegewisch'),
 (0.0004647501220402497, 'Location_Description_WAREHOUSE'),
 (0.0004368638276311597, 'Community_Area_Name_Hyde Park'),
 (0.0004235129142014191, 'Location_Description_VEHICLE-COMMERCIAL'),
 (0.00040878296104895066, 'Community_Area_Name_Forest Glen'),
 (0.0003875775313759707, 'Primary_Type_HOMICIDE'),
 (0.0003851295336160693, 'Community_Area_Name_Norwood Park'),
 (0.00038474639042706047, 'Community_Area_Name_North Center'),
 (0.00038457286429412717, 'Community_Area_Name_Jefferson Park'),
 (0.00038384467191196904, 'Location_Description_CURRENCY EXCHANGE'),
 (0.00038230029044829776, 'Community_Area_Name_Beverly'),
 (0.00036303026815563845, 'Location_Description_COLLEGE/UNIVERSITY GROUNDS'),
 (0.00035822314251141626, 'Location_Description_SCHOOL, PRIVATE, GROUNDS'),
 (0.00035175981709935345, 'Location_Description_ATHLETIC CLUB'),
 (0.00034938668744694706,
  'Location_Description_OTHER COMMERCIAL TRANSPORTATION'),
 (0.00034731115491518636,
  'Location_Description_CHA HALLWAY/STAIRWELL/ELEVATOR'),
 (0.0003418402844424453, 'Community_Area_Name_Mount Greenwood'),
 (0.00033511310775685525,
  'Location_Description_AIRPORT TERMINAL UPPER LEVEL - SECURE AREA'),
 (0.0003322422854871223, 'Community_Area_Name_Burnside'),
 (0.00032475710290320083, 'Location_Description_CAR WASH'),
 (0.00031633982837447834, 'Community_Area_Name_Montclaire'),
 (0.0003125515707475128, 'Community_Area_Name_Clearing'),
 (0.0003078630596397008, 'Primary_Type_ARSON'),
 (0.0003050173861392206, 'Location_Description_MOVIE HOUSE/THEATER'),
 (0.0003002944979227331, 'Primary_Type_KIDNAPPING'),
 (0.00029218496236645754, 'Location_Description_JAIL / LOCK-UP FACILITY'),
 (0.00026619370052581256, 'Community_Area_Name_Oakland'),
 (0.00024984485960209186, 'Location_Description_CTA TRACKS - RIGHT OF WAY'),
 (0.0002479849212800802,
  'Location_Description_VEHICLE - OTHER RIDE SHARE SERVICE (E.G., UBER, LYFT)'),
 (0.0002464178504389815, 'Location_Description_SPORTS ARENA/STADIUM'),
 (0.00023345458345764143,
  'Location_Description_AIRPORT TERMINAL LOWER LEVEL - NON-SECURE AREA'),
 (0.00022962471044622826, 'Location_Description_DAY CARE CENTER'),
 (0.00022475536366813552, 'FBI_Code_13'),
 (0.00022022650862719853, 'Location_Description_PAWN SHOP'),
 (0.00021945100154276433, 'Location_Description_ANIMAL HOSPITAL'),
 (0.0002116334471664617, 'FBI_Code_9'),
 (0.00020996561927504373, 'Primary_Type_STALKING'),
 (0.00019885972734908863, 'Primary_Type_PUBLIC INDECENCY'),
 (0.0001939650283552975, 'Location_Description_MEDICAL/DENTAL OFFICE'),
 (0.00019149949229025907,
  'Location_Description_AIRPORT BUILDING NON-TERMINAL - NON-SECURE AREA'),
 (0.000191112422900878, 'Primary_Type_INTIMIDATION'),
 (0.0001770519258478847,
  'Location_Description_FACTORY/MANUFACTURING BUILDING'),
 (0.0001763336513462396, 'Community_Area_Name_Edison Park'),
 (0.0001740964546589827, 'Location_Description_HIGHWAY/EXPRESSWAY'),
 (0.00015932536888752058, 'Location_Description_HOUSE'),
 (0.00015748066454833814,
  'Location_Description_AIRPORT TERMINAL UPPER LEVEL - NON-SECURE AREA'),
 (0.00012529604559567876,
  'Location_Description_ATM (AUTOMATIC TELLER MACHINE)'),
 (0.00012425512699922484, 'Location_Description_FEDERAL BUILDING'),
 (0.00011263893571620657, 'Location_Description_AIRPORT PARKING LOT'),
 (0.00010050019820349129,
  'Location_Description_VEHICLE-COMMERCIAL - ENTERTAINMENT/PARTY BUS'),
 (9.73395627025166e-05,
  'Location_Description_AIRPORT EXTERIOR - NON-SECURE AREA'),
 (9.472565941323089e-05, 'Location_Description_CLEANING STORE'),
 (7.620859827829543e-05, 'Location_Description_AIRCRAFT'),
 (7.16013945303855e-05, 'Location_Description_BRIDGE'),
 (6.888642423166009e-05, 'Location_Description_FIRE STATION'),
 (6.352645211513114e-05, 'FBI_Code_01B'),
 (6.24927297209127e-05, 'Location_Description_AIRPORT VENDING ESTABLISHMENT'),
 (5.6105536714317804e-05, 'Location_Description_SAVINGS AND LOAN'),
 (5.544903889702015e-05, 'Primary_Type_NON-CRIMINAL'),
 (4.4535787324197957e-05, 'Location_Description_BOWLING ALLEY'),
 (3.814828331630844e-05, 'Location_Description_CTA PROPERTY'),
 (3.697604557298249e-05, 'Location_Description_CEMETARY'),
 (3.59580697422637e-05, 'Location_Description_PARKING LOT'),
 (3.5285369228038516e-05, 'Location_Description_COIN OPERATED MACHINE'),
 (3.43702046318228e-05, 'Location_Description_GOVERNMENT BUILDING'),
 (3.360079656284093e-05, 'Location_Description_GARAGE'),
 (3.2401787315869485e-05, 'Location_Description_PORCH'),
 (3.1896767183697796e-05,
  'Location_Description_AIRPORT BUILDING NON-TERMINAL - SECURE AREA'),
 (3.1220703980004684e-05, 'Location_Description_AUTO'),
 (2.9694066605789996e-05, 'FBI_Code_12'),
 (2.934014701737658e-05, 'Primary_Type_HUMAN TRAFFICKING'),
 (2.8978677995656497e-05,
  'Location_Description_AIRPORT TERMINAL LOWER LEVEL - SECURE AREA'),
 (2.8970358206601054e-05,
  'Location_Description_COLLEGE/UNIVERSITY RESIDENCE HALL'),
 (2.4700762660364194e-05, 'Location_Description_BOAT/WATERCRAFT'),
 (2.4444594849279228e-05, 'Primary_Type_NON-CRIMINAL (SUBJECT SPECIFIED)'),
 (1.9493446240992882e-05, 'Location_Description_POOL ROOM'),
 (1.9165397049216717e-05,
  'Location_Description_LAKEFRONT/WATERFRONT/RIVERBANK'),
 (1.4409230925584502e-05,
  'Location_Description_AIRPORT EXTERIOR - SECURE AREA'),
 (9.873080847764147e-06, 'Location_Description_VEHICLE - DELIVERY TRUCK'),
 (8.445756630599508e-06, 'Location_Description_GARAGE/AUTO REPAIR'),
 (6.251084558838823e-06, 'Location_Description_AIRPORT/AIRCRAFT'),
 (5.11333734383018e-06, 'Location_Description_HALLWAY'),
 (4.924031967464828e-06,
  'Location_Description_AIRPORT TERMINAL MEZZANINE - NON-SECURE AREA'),
 (4.088203444908562e-06, 'Location_Description_HOTEL'),
 (2.8882647077906777e-06, 'Location_Description_YARD'),
 (2.759556423031816e-06, 'Location_Description_LIQUOR STORE'),
 (2.289942428079e-06, 'Location_Description_VEHICLE-COMMERCIAL - TROLLEY BUS'),
 (2.2113171637563267e-06, 'Location_Description_CHA GROUNDS'),
 (1.7581413991619081e-06,
  'Location_Description_AIRPORT TRANSPORTATION SYSTEM (ATS)'),
 (1.6619430885500657e-06, 'Location_Description_FOREST PRESERVE'),
 (1.5099038437272104e-06, 'Location_Description_CREDIT UNION'),
 (7.463265139708931e-07, 'Location_Description_VACANT LOT'),
 (6.758219660160858e-07, 'Location_Description_FARM'),
 (6.37723011744584e-07, 'Location_Description_NEWSSTAND'),
 (0.0, 'Location_Description_YMCA'),
 (0.0, 'Location_Description_RETAIL STORE'),
 (0.0, 'Location_Description_HORSE STABLE'),
 (0.0, 'Location_Description_DRIVEWAY')]